### ISSUE TITLE
Fix header menu inconsistencies

### ISSUE THREAD

**Issue by JuanCAlpizar** [alex285/re-l#9]
In native GTK apps the menu header color blends with the title bar as expected, screenshot as a reference

![image](https://user-images.githubusercontent.com/2028118/33384969-1392036a-d4ed-11e7-8587-7bf99108c52b.png)

However in electron based apps, the menu renders in white background
![image](https://user-images.githubusercontent.com/2028118/33385012-30f4a6e2-d4ed-11e7-82ae-6d3a0965ff48.png)

On a side note, is there a good reference material to learn on building themes? :) I'd like to get into it and helping on this one if possible on my free time 👍

**Comment by alex285** [comment]
that happens because VSC uses GTK 2.0, and for GTK 2.0 i just use Adwaita default, so there isn't something i can do for that! however VSC will be ported on GTK 3.0 soon ..i hope!

im not aware of themes guides, but it is not needed really. it is just Sass code. if you look on themes source, it is straight forward to understand how it works!

**Comment by JuanCAlpizar** [comment]
@alex285  ah, I just used Visual Studio Code as a reference, but it happens in all of the electron apps I have: Expo XDE, VSC, Skype for Linux, Evernote Tusk... you name it, are all of the electron apps constrained to GTK2 2.0? 

I used to open the Sass files once in the past but there were so many different classes and almost no documentation, is there any tool I can at least preview what belongs to where? Does it work only with the GTK apps, or does it also work to preview GDM to help on theming it, does it support shell? Well in case such tool exists :p

**Comment by alex285** [comment]
@JuanCAlpizar yes it happens to all Electron apps, because it is Electron that uses GTK2. However Electron next version is ported to GTK 3, so all these apps, when they update their Electron, they will use the GTK 3.0 theme ..hopefully everyone will update inside a few months

you can use GTK inspector. Open Dconf-Editor and go to:
`/org/gtk/settings/debug/`

enable keybinding shortcut, and after in every GTK app press `Shift+Ctrl+i` or `d`
after that point you will figure out how it works! which is like Chromium tools more or less!

btw if you use Re-L, here is a [more fresh copy](https://ufile.io/elyts) ..i also included Re-L SourceView theme 

copy it to: `~/.local/share/gtksourceview-3.0/styles` and then select it in Gedit for example

inside the weekend i hope i will publish the theme with new assets, so it will get usable :)
